### ISSUE TITLE
make build_docs fails

### ISSUE THREAD

**Issue by bulli92** [pygeo/pycmbs#12]
with the following message:

(ipythondev)m300028@alexnotebook:pycmbs$ make build_docs 
python setup.py build_sphinx
running build_sphinx
Running Sphinx v1.2b3
/home/m300028/virtualenvs/ipythondev/local/lib/python2.7/site-packages/matplotlib-1.4.x-py2.7-linux-x86_64.egg/matplotlib/cbook.py:126: MatplotlibDeprecationWarning: 
The Sphinx extension ipython_console_highlighting has moved from
matplotlib to IPython, and its use in matplotlib is deprecated.
Change your import from 'matplotlib.sphinxext.ipython_directive' to
'IPython.sphinxext.ipython_directive.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    license="MIT license")
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/setup_command.py", line 143, in run
    freshenv=self.fresh_env)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 119, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 283, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/m300028/virtualenvs/ipythondev/local/lib/python2.7/site-packages/matplotlib-1.4.x-py2.7-linux-x86_64.egg/matplotlib/sphinxext/ipython_directive.py", line 534, in <module>
    class IpythonDirective(Directive):
  File "/home/m300028/virtualenvs/ipythondev/local/lib/python2.7/site-packages/matplotlib-1.4.x-py2.7-linux-x86_64.egg/matplotlib/sphinxext/ipython_directive.py", line 546, in IpythonDirective
    shell = EmbeddedSphinxShell()
  File "/home/m300028/virtualenvs/ipythondev/local/lib/python2.7/site-packages/matplotlib-1.4.x-py2.7-linux-x86_64.egg/matplotlib/sphinxext/ipython_directive.py", line 208, in __init__
    self.cout = io.StringIO()
AttributeError: 'module' object has no attribute 'StringIO'
make: *** [build_docs] Error 1

**Comment by bulli92** [comment]
Has been fixed by removin dependency on matplotlib extensions.
